contentColumnType: text
fieldGroup: 47460a21-8d89-4b87-856d-45d3554ede5c
handle: pageCopy
instructions: ''
name: 'Page Copy'
searchable: false
settings:
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
